In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("C:/Users/coding/Downloads/export.csv", index_col=0)

In [24]:
df.columns

Index(['Score', 'Export End Trial Time [ms]', 'Visual Intake Count',
       'Visual Intake Frequency [count/s]',
       'Visual Intake Duration Total [ms]',
       'Visual Intake Duration Average [ms]',
       'Visual Intake Duration Maximum [ms]',
       'Visual Intake Duration Minimum [ms]',
       'Visual Intake Dispersion Total [px]',
       'Visual Intake Dispersion Average [px]',
       'Visual Intake Dispersion Maximum [px]',
       'Visual Intake Dispersion Minimum [px]', 'Saccade Count',
       'Saccade Frequency [count/s]', 'Saccade Duration Total [ms]',
       'Saccade Duration Average [ms]', 'Saccade Duration Maximum [ms]',
       'Saccade Duration Minimum [ms]', 'Saccade Amplitude Total [°]',
       'Saccade Amplitude Average [°]', 'Saccade Amplitude Maximum [°]',
       'Saccade Amplitude Minimum [°]', 'Saccade Velocity Total [°/s]',
       'Saccade Velocity Average [°/s]', 'Saccade Velocity Maximum [°/s]',
       'Saccade Velocity Minimum [°/s]', 'Saccade Latency Average

In [25]:
y=df['median_split']
X=df[['Visual Intake Count',
       'Visual Intake Frequency [count/s]',
       'Visual Intake Duration Total [ms]',
       'Visual Intake Duration Average [ms]',
       'Visual Intake Duration Maximum [ms]',
       'Visual Intake Duration Minimum [ms]',
       'Visual Intake Dispersion Total [px]',
       'Visual Intake Dispersion Average [px]',
       'Visual Intake Dispersion Maximum [px]',
       'Visual Intake Dispersion Minimum [px]', 'Saccade Count',
       'Saccade Frequency [count/s]', 'Saccade Duration Total [ms]',
       'Saccade Duration Average [ms]', 'Saccade Duration Maximum [ms]',
       'Saccade Duration Minimum [ms]', 'Saccade Amplitude Total [°]',
       'Saccade Amplitude Average [°]', 'Saccade Amplitude Maximum [°]',
       'Saccade Amplitude Minimum [°]', 'Saccade Velocity Total [°/s]',
       'Saccade Velocity Average [°/s]', 'Saccade Velocity Maximum [°/s]',
       'Saccade Velocity Minimum [°/s]', 'Saccade Latency Average [ms]',
       'Blink Count', 'Blink Frequency [count/s]', 'Blink Duration Total [ms]',
       'Blink Duration Average [ms]', 'Blink Duration Maximum [ms]',
       'Blink Duration Minimum [ms]', 'Scanpath Length [px]','PERCLOS']]

In [26]:
df

Score  Export End Trial Time [ms]  \
Export Start Trial Time [ms]                                      
0.0                              15                     94361.4   
0.0                              15                    526819.8   
0.0                               6                     11932.0   
0.0                               6                    441586.0   
0.0                               6                      2589.1   
0.0                              12                     11235.2   
0.0                              12                    444357.7   
0.0                              12                      1958.2   
0.0                              10                    799034.0   
0.0                              10                    876152.6   
0.0                              10                      4481.0   
0.0                               2                    444141.8   
0.0                              15                    816956.8   
0.0                              15                    444058.6   
0.0                              10                     38235.7   
0.0                              12                     24777.0   
0.0                              12                    497910.7   
0.0                              12                    829718.3   
0.0                              12                    449037.1   
0.0                              12                     28942.4   
0.0                              12                    437752.5   
0.0                              12                    496815.5   
0.0                               9                     37688.0   
0.0                               9                    465997.6   
0.0                              15                    483920.8   
0.0                              15                     94361.4   
0.0                              15                    526819.8   
0.0                              15                    434733.0   
0.0                              11                    881097.6   
0.0                              11                    474079.7   
0.0                               9                    479174.4   
0.0                               7                    104567.5   
0.0                               7                    395085.7   
0.0                               9                    439445.4   
0.0                               9                    439428.8   
0.0                              10                    460438.1   
0.0                              12                    513892.1   
0.0                              12                    453850.1   
0.0                              10                    445668.7   
0.0                              15                    467774.0   
0.0                              12                    462280.7   
0.0                              12                      1178.6   
0.0                              15                      3966.4   
0.0                              15                    475506.9   
0.0                              15                    451161.5   

                              Visual Intake Count  \
Export Start Trial Time [ms]                        
0.0                                         111.0   
0.0                                         156.0   
0.0                                          36.0   
0.0                                        1119.0   
0.0                                           6.0   
0.0                                          27.0   
0.0                                         990.0   
0.0                                           0.0   
0.0                                        1628.0   
0.0                                        1658.0   
0.0                                          10.0   
0.0                                         923.0   
0.0                                        1556.0   
0.0                                        1190.0   
0.0                             

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler



X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    shuffle=True,
                                                    )



scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [28]:
from sklearn.svm import SVC

svclassifier2 = SVC(kernel='linear')
svclassifier2.fit(X_train, y_train)


SVC(kernel='linear')

In [29]:
y_pred = svclassifier2.predict(X_test)

In [30]:
y_pred

array([1., 0., 1., 0., 0., 0., 1., 1., 0.])

In [31]:
from sklearn.metrics import classification_report, confusion_matrix

print('-'*30)
print('Classification Report for SVM for Experiment 2 :')
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('-'*30)

------------------------------
Classification Report for SVM for Experiment 2 :
[[2 2]
 [3 2]]
              precision    recall  f1-score   support

         0.0       0.40      0.50      0.44         4
         1.0       0.50      0.40      0.44         5

    accuracy                           0.44         9
   macro avg       0.45      0.45      0.44         9
weighted avg       0.46      0.44      0.44         9

------------------------------


In [32]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X_train,y_train)

#Predict Output
y_knn_pred= model.predict(X_test) # 0:Overcast, 2:Mild
print(y_knn_pred)

[0. 1. 1. 0. 0. 1. 1. 0. 1.]


In [33]:
print('-'*30)
print('Classification Report for KNN for Experiment 2 :')
print(confusion_matrix(y_test,y_knn_pred))
print(classification_report(y_test,y_knn_pred))
print('-'*30)

------------------------------
Classification Report for KNN for Experiment 2 :
[[3 1]
 [1 4]]
              precision    recall  f1-score   support

         0.0       0.75      0.75      0.75         4
         1.0       0.80      0.80      0.80         5

    accuracy                           0.78         9
   macro avg       0.78      0.78      0.78         9
weighted avg       0.78      0.78      0.78         9

------------------------------


In [34]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred_lr2 = model.predict(X_test)
print('-'*30)
print('Classification Result for Logistic Regression  :')
print(classification_report(y_test, pred_lr2))
print('-'*40)

------------------------------
Classification Result for Logistic Regression  :
              precision    recall  f1-score   support

         0.0       0.33      0.25      0.29         4
         1.0       0.50      0.60      0.55         5

    accuracy                           0.44         9
   macro avg       0.42      0.42      0.42         9
weighted avg       0.43      0.44      0.43         9

----------------------------------------


Decision tree

In [35]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
pred_dt2 = dt.predict(X_test)


print('-'*30)
print('Classification result for Decision Tree for second experiment :')
print(classification_report(y_test, pred_dt2))
print('-'*40)

------------------------------
Classification result for Decision Tree for second experiment :
              precision    recall  f1-score   support

         0.0       0.33      0.50      0.40         4
         1.0       0.33      0.20      0.25         5

    accuracy                           0.33         9
   macro avg       0.33      0.35      0.33         9
weighted avg       0.33      0.33      0.32         9

----------------------------------------


In [36]:
 from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(n_estimators=50,
                         learning_rate=3
                         )
# Train Adaboost Classifer
model2 = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_abc = model2.predict(X_test)

print('-'*30)
print('Classification Results for AdaBoost for second Experiment:')
print(classification_report(y_test, y_pred_abc))
print('-'*40)

------------------------------
Classification Results for AdaBoost for second Experiment:
              precision    recall  f1-score   support

         0.0       0.38      0.75      0.50         4
         1.0       0.00      0.00      0.00         5

    accuracy                           0.33         9
   macro avg       0.19      0.38      0.25         9
weighted avg       0.17      0.33      0.22         9

----------------------------------------
