In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_exp3=pd.read_csv("C:/Users/coding/Downloads/export.csv", index_col=0)

In [3]:
df_ques=pd.read_csv("C:/Users/coding/Downloads/personality questionnaire Responses - Sheet1.csv")  

In [4]:
df_ques

Gender   Age  Extraverted, enthusiastic.  Critical, quarrelsome.  \
0   Woman  26.0                         5.0                     3.0   
1   Woman  26.0                         5.0                     3.0   
2     Man  29.0                         4.0                     2.0   
3     Man  29.0                         4.0                     2.0   
4     Man  29.0                         4.0                     2.0   
5     Man  31.0                         2.0                     1.0   
6     Man  31.0                         2.0                     1.0   
7     Man  31.0                         2.0                     1.0   
8     Man  23.0                         4.0                     3.0   
9     Man  27.0                         3.0                     4.0   
10    Man  27.0                         3.0                     4.0   
11  Woman  26.0                         3.0                     3.0   
12    Man  23.0                         5.0                     5.0   
13    Man  28.0                         7.0                     4.0   
14    Man  28.0                         5.0                     5.0   
15  Woman  23.0                         6.0                     1.0   
16  Woman  23.0                         6.0                     1.0   
17    Man  28.0                         2.0                     4.0   
18    Man  28.0                         2.0                     4.0   
19    Man  24.0                         3.0                     4.0   
20    Man  24.0                         3.0                     4.0   
21    Man  26.0                         4.0                     4.0   
22    Man  26.0                         5.0                     5.0   
23    Man  26.0                         5.0                     5.0   
24    Man  19.0                         4.0                     6.0   
25  Woman  26.0                         5.0                     3.0   
26  Woman  26.0                         5.0                     3.0   
27    Man  28.0                         4.0                     5.0   
28    Man  26.0                         4.0                     4.0   
29    Man  26.0                         4.0                     4.0   
30  Woman  28.0                         4.0                     4.0   
31    Man  21.0                         3.0                     1.0   
32    Man  21.0                         3.0                     1.0   
33  Woman  43.0                         4.0                     4.0   
34    Man  43.0                         5.0                     5.0   
35    Man  22.0                         7.0                     2.0   
36    Man  25.0                         5.0                     4.0   
37    Man  25.0                         5.0                     4.0   
38    Man  27.0                         3.0                     4.0   
39    Man  23.0                         5.0                     5.0   
40  Woman  52.0                         5.0                     2.0   
41  Woman  52.0                         5.0                     2.0   
42    Man  28.0                         6.0                     4.0   
43    Man  28.0                         6.0                     4.0   
44    Man  28.0                         6.0                     2.0   

    Dependable, self-disciplined.  Anxious, easily upset  \
0                             4.0                    5.0   
1                             4.0                    5.0   
2                             6.0                    5.0   
3                             6.0                    5.0   
4                             6.0                    5.0   
5                             1.0                    6.0   
6                             1.0                    6.0   
7                             1.0                    6.0   
8                             6.0                    2.0   
9                             4.0                    6.0   
10                            4.0                    6.0   
11              

In [5]:
##transformation
df_ques.loc[df_ques["Gender"] == "Man", "Gender"] = 1
df_ques.loc[df_ques["Gender"] == "Woman", "Gender"] = 0

In [6]:
df_ques

Gender   Age  Extraverted, enthusiastic.  Critical, quarrelsome.  \
0       0  26.0                         5.0                     3.0   
1       0  26.0                         5.0                     3.0   
2       1  29.0                         4.0                     2.0   
3       1  29.0                         4.0                     2.0   
4       1  29.0                         4.0                     2.0   
5       1  31.0                         2.0                     1.0   
6       1  31.0                         2.0                     1.0   
7       1  31.0                         2.0                     1.0   
8       1  23.0                         4.0                     3.0   
9       1  27.0                         3.0                     4.0   
10      1  27.0                         3.0                     4.0   
11      0  26.0                         3.0                     3.0   
12      1  23.0                         5.0                     5.0   
13      1  28.0                         7.0                     4.0   
14      1  28.0                         5.0                     5.0   
15      0  23.0                         6.0                     1.0   
16      0  23.0                         6.0                     1.0   
17      1  28.0                         2.0                     4.0   
18      1  28.0                         2.0                     4.0   
19      1  24.0                         3.0                     4.0   
20      1  24.0                         3.0                     4.0   
21      1  26.0                         4.0                     4.0   
22      1  26.0                         5.0                     5.0   
23      1  26.0                         5.0                     5.0   
24      1  19.0                         4.0                     6.0   
25      0  26.0                         5.0                     3.0   
26      0  26.0                         5.0                     3.0   
27      1  28.0                         4.0                     5.0   
28      1  26.0                         4.0                     4.0   
29      1  26.0                         4.0                     4.0   
30      0  28.0                         4.0                     4.0   
31      1  21.0                         3.0                     1.0   
32      1  21.0                         3.0                     1.0   
33      0  43.0                         4.0                     4.0   
34      1  43.0                         5.0                     5.0   
35      1  22.0                         7.0                     2.0   
36      1  25.0                         5.0                     4.0   
37      1  25.0                         5.0                     4.0   
38      1  27.0                         3.0                     4.0   
39      1  23.0                         5.0                     5.0   
40      0  52.0                         5.0                     2.0   
41      0  52.0                         5.0                     2.0   
42      1  28.0                         6.0                     4.0   
43      1  28.0                         6.0                     4.0   
44      1  28.0                         6.0                     2.0   

    Dependable, self-disciplined.  Anxious, easily upset  \
0                             4.0                    5.0   
1                             4.0                    5.0   
2                             6.0                    5.0   
3                             6.0                    5.0   
4                             6.0                    5.0   
5                             1.0                    6.0   
6                             1.0                    6.0   
7                             1.0                    6.0   
8                             6.0                    2.0   
9                             4.0                    6.0   
10                            4.0                    6.0   
11              

In [7]:
df_ques.dtypes

Gender                                                                                                                                        object
Age                                                                                                                                          float64
Extraverted, enthusiastic.                                                                                                                   float64
Critical, quarrelsome.                                                                                                                       float64
Dependable, self-disciplined.                                                                                                                float64
Anxious, easily upset                                                                                                                        float64
Open to new experiences, complex                                                                          

In [9]:
df_ques['Gender'] = df_ques['Gender'].astype(int)

In [10]:
df_ques.dtypes

Gender                                                                                                                                         int32
Age                                                                                                                                          float64
Extraverted, enthusiastic.                                                                                                                   float64
Critical, quarrelsome.                                                                                                                       float64
Dependable, self-disciplined.                                                                                                                float64
Anxious, easily upset                                                                                                                        float64
Open to new experiences, complex                                                                          

In [11]:
df_exp3=df_exp3[['Export End Trial Time [ms]', 'Visual Intake Count',
       'Visual Intake Frequency [count/s]',
       'Visual Intake Duration Total [ms]',
       'Visual Intake Duration Average [ms]',
       'Visual Intake Duration Maximum [ms]',
       'Visual Intake Duration Minimum [ms]',
       'Visual Intake Dispersion Total [px]',
       'Visual Intake Dispersion Average [px]',
       'Visual Intake Dispersion Maximum [px]',
       'Visual Intake Dispersion Minimum [px]', 'Saccade Count',
       'Saccade Frequency [count/s]', 'Saccade Duration Total [ms]',
       'Saccade Duration Average [ms]', 'Saccade Duration Maximum [ms]',
       'Saccade Duration Minimum [ms]', 'Saccade Amplitude Total [°]',
       'Saccade Amplitude Average [°]', 'Saccade Amplitude Maximum [°]',
       'Saccade Amplitude Minimum [°]', 'Saccade Velocity Total [°/s]',
       'Saccade Velocity Average [°/s]', 'Saccade Velocity Maximum [°/s]',
       'Saccade Velocity Minimum [°/s]', 'Saccade Latency Average [ms]',
       'Blink Count', 'Blink Frequency [count/s]', 'Blink Duration Total [ms]',
       'Blink Duration Average [ms]', 'Blink Duration Maximum [ms]',
       'Blink Duration Minimum [ms]', 'Scanpath Length [px]', 'median_split',
       'PERCLOS']]

In [12]:
df_exp3.columns

Index(['Export End Trial Time [ms]', 'Visual Intake Count',
       'Visual Intake Frequency [count/s]',
       'Visual Intake Duration Total [ms]',
       'Visual Intake Duration Average [ms]',
       'Visual Intake Duration Maximum [ms]',
       'Visual Intake Duration Minimum [ms]',
       'Visual Intake Dispersion Total [px]',
       'Visual Intake Dispersion Average [px]',
       'Visual Intake Dispersion Maximum [px]',
       'Visual Intake Dispersion Minimum [px]', 'Saccade Count',
       'Saccade Frequency [count/s]', 'Saccade Duration Total [ms]',
       'Saccade Duration Average [ms]', 'Saccade Duration Maximum [ms]',
       'Saccade Duration Minimum [ms]', 'Saccade Amplitude Total [°]',
       'Saccade Amplitude Average [°]', 'Saccade Amplitude Maximum [°]',
       'Saccade Amplitude Minimum [°]', 'Saccade Velocity Total [°/s]',
       'Saccade Velocity Average [°/s]', 'Saccade Velocity Maximum [°/s]',
       'Saccade Velocity Minimum [°/s]', 'Saccade Latency Average [ms]',
 

In [13]:
df_exp3.insert(0, 'Experiment no', range(1, 1 + len(df_exp3)))
df_exp3.set_index('Experiment no',inplace=True)

In [14]:
df3_final= pd.concat([df_exp3, df_ques], axis=1, join='inner')
display(df3_final)

Export End Trial Time [ms]  Visual Intake Count  \
1                      94361.4                111.0   
2                     526819.8                156.0   
3                      11932.0                 36.0   
4                     441586.0               1119.0   
5                       2589.1                  6.0   
6                      11235.2                 27.0   
7                     444357.7                990.0   
8                       1958.2                  0.0   
9                     799034.0               1628.0   
10                    876152.6               1658.0   
11                      4481.0                 10.0   
12                    444141.8                923.0   
13                    816956.8               1556.0   
14                    444058.6               1190.0   
15                     38235.7                 89.0   
16                     24777.0                 39.0   
17                    497910.7               1284.0   
18                    829718.3               1492.0   
19                    449037.1                982.0   
20                     28942.4                 77.0   
21                    437752.5                828.0   
22                    496815.5               1266.0   
23                     37688.0                 87.0   
24                    465997.6                841.0   
25                    483920.8                855.0   
26                     94361.4                111.0   
27                    526819.8                156.0   
28                    434733.0                815.0   
29                    881097.6               1671.0   
30                    474079.7               1002.0   
31                    479174.4               1210.0   
32                    104567.5                260.0   
33                    395085.7                188.0   
34                    439445.4               1180.0   
35                    439428.8               1026.0   
36                    460438.1                985.0   
37                    513892.1               1050.0   
38                    453850.1                842.0   
39                    445668.7                877.0   
40                    467774.0                781.0   
41                    462280.7                 11.0   
42                      1178.6                  0.0   
43                      3966.4                  4.0   
44                    475506.9               1191.0   

    Visual Intake Frequency [count/s]  Visual Intake Duration Total [ms]  \
1                                 1.2                            59592.8   
2                                 0.3                            20084.1   
3                                 3.0                             9576.4   
4                                 2.5                           354798.9   
5                                 2.3                             1826.1   
6                                 2.4                             8030.0   
7                                 2.2                           389227.5   
8                                 0.0                                0.0   
9                                 2.0                           692142.9   
10                                1.9                           716097.6   
11                                2.2                             3933.5   
12                                2.1                           384038.8   
13                                1.9                           595295.0   
14                                2.7                           381279.1   
15                                2.3                            23947.1   
16                                1.6                            12697.4   
17                                2.6                           427506.1   
18                                1.8                           746285.9   
19                                2.2                           400792.2   
20      

In [17]:
y3=df3_final['median_split']
X3=df3_final.drop('median_split',axis = 1)

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler



X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    shuffle=True,
                                                    )



scaler = StandardScaler()
X3_train=scaler.fit_transform(X3_train)
X3_test=scaler.fit_transform(X3_test)

SVM

In [19]:
from sklearn.svm import SVC

svclassifier3 = SVC(kernel='linear')
svclassifier3.fit(X3_train, y3_train)

SVC(kernel='linear')

In [20]:
y3_pred = svclassifier3.predict(X3_test)

In [21]:
y3_pred

array([0., 0., 1., 0., 0., 1., 0., 1., 1.])

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

print('-'*30)
print('Classification Report for SVM for Experiment 3 :')
print(confusion_matrix(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))
print('-'*30)

------------------------------
Classification Report for SVM for Experiment 3 :
[[3 1]
 [2 3]]
              precision    recall  f1-score   support

         0.0       0.60      0.75      0.67         4
         1.0       0.75      0.60      0.67         5

    accuracy                           0.67         9
   macro avg       0.68      0.68      0.67         9
weighted avg       0.68      0.67      0.67         9

------------------------------


KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X3_train,y3_train)

#Predict Output
y3_knn_pred= model.predict(X3_test) # 0:Overcast, 2:Mild
print(y3_knn_pred)


[0. 1. 1. 1. 0. 1. 1. 0. 1.]


In [24]:
print('-'*30)
print('Classification Report for KNN for Experiment 3 :')
print(confusion_matrix(y3_test,y3_knn_pred))
print(classification_report(y3_test,y3_knn_pred))
print('-'*30)

------------------------------
Classification Report for KNN for Experiment 3 :
[[2 2]
 [1 4]]
              precision    recall  f1-score   support

         0.0       0.67      0.50      0.57         4
         1.0       0.67      0.80      0.73         5

    accuracy                           0.67         9
   macro avg       0.67      0.65      0.65         9
weighted avg       0.67      0.67      0.66         9

------------------------------


Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X3_train,y3_train)
pred_lr3 = model.predict(X3_test)
print('-'*30)
print('Classification Report for Logistic Regression for experiment 3 :')
print(classification_report(y3_test, pred_lr3))
print('-'*40)

------------------------------
Classification Report for Logistic Regression for experiment 3 :
              precision    recall  f1-score   support

         0.0       1.00      0.75      0.86         4
         1.0       0.83      1.00      0.91         5

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9

----------------------------------------


In [26]:
print('-'*30)
print('Classification Report for Logistic Regression for Experiment 3 :')
print(confusion_matrix(y3_test,pred_lr3))
print(classification_report(y3_test,pred_lr3))
print('-'*30)

------------------------------
Classification Report for Logistic Regression for Experiment 3 :
[[3 1]
 [0 5]]
              precision    recall  f1-score   support

         0.0       1.00      0.75      0.86         4
         1.0       0.83      1.00      0.91         5

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9

------------------------------


Decision Tree

In [27]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X3_train,y3_train)
pred_dt3 = dt.predict(X3_test)


print('-'*30)
print('Classification Report for Decision Tree for Experiment 3 :')
print(classification_report(y3_test, pred_dt3))
print('-'*40)

------------------------------
Classification Report for Decision Tree for Experiment 3 :
              precision    recall  f1-score   support

         0.0       1.00      0.50      0.67         4
         1.0       0.71      1.00      0.83         5

    accuracy                           0.78         9
   macro avg       0.86      0.75      0.75         9
weighted avg       0.84      0.78      0.76         9

----------------------------------------


Ada Boost

In [28]:
from sklearn.ensemble import AdaBoostClassifier

abc3 = AdaBoostClassifier(n_estimators=50,
                         learning_rate=3)
# Train Adaboost Classifer
model3 = abc3.fit(X3_train, y3_train)

#Predict the response for test dataset
y_pred_abc3 = model3.predict(X3_test)

print('-'*30)
print('Classification Report for AdaBoost for Experiment 3 :')
print(classification_report(y3_test, y_pred_abc3))
print('-'*40)

------------------------------
Classification Report for AdaBoost for Experiment 3 :
              precision    recall  f1-score   support

         0.0       0.60      0.75      0.67         4
         1.0       0.75      0.60      0.67         5

    accuracy                           0.67         9
   macro avg       0.68      0.68      0.67         9
weighted avg       0.68      0.67      0.67         9

----------------------------------------
